// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtNbsWz6uAYjJwa_fVUhp6dfTMtdqxx7k',
    appId: '1:410737495286:web:40390428af999c1e8970d7',
    messagingSenderId: '410737495286',
    projectId: 'spot-seven-22acd',
    authDomain: 'spot-seven-22acd.firebaseapp.com',
    storageBucket: 'spot-seven-22acd.appspot.com',
    measurementId: 'G-W5XZQ2LS8Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMJgn_zxin1bwbxfsmFUYnT7Kv8nFbXFA',
    appId: '1:410737495286:android:ea284f066978896b8970d7',
    messagingSenderId: '410737495286',
    projectId: 'spot-seven-22acd',
    storageBucket: 'spot-seven-22acd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAl2iaer9OJSOtmnA3tblkZIyeWOvc917M',
    appId: '1:410737495286:ios:a02a284fdde09ff08970d7',
    messagingSenderId: '410737495286',
    projectId: 'spot-seven-22acd',
    storageBucket: 'spot-seven-22acd.appspot.com',
    iosClientId: '410737495286-gvkpfh7piiemk99a7qqp4tmdaso497p9.apps.googleusercontent.com',
    iosBundleId: 'com.example.clientLeger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAl2iaer9OJSOtmnA3tblkZIyeWOvc917M',
    appId: '1:410737495286:ios:2bd0fffc9098ce4d8970d7',
    messagingSenderId: '410737495286',
    projectId: 'spot-seven-22acd',
    storageBucket: 'spot-seven-22acd.appspot.com',
    iosClientId: '410737495286-gup6mjm6ms0ro7mfs4stb9160f6fn19f.apps.googleusercontent.com',
    iosBundleId: 'com.example.clientLeger.RunnerTests',
  );
}
